"""Emit the vendored halo2_poseidon test fixture consumed by ragu_primitives.

Reads a halo2 checkout and writes
`crates/ragu_primitives/src/poseidon_halo2_vectors.rs`: the P128Pow5T3
parameters (t=3) for both Pasta base fields, and halo2's permutation test
vectors, which come from zcash-test-vectors' `orchard_poseidon/permute`.

    python3 qa/params/gen_halo2_vectors.py --halo2-dir path/to/halo2

The output is checked in, so a halo2 checkout is only needed to regenerate it.
"""

import argparse
import re
import sys
from pathlib import Path

FROM_RAW = re.compile(r"from_raw\(\[\s*((?:0x[0-9a-fA-F_]+,\s*){4})\]\)", re.MULTILINE)
BYTE_ARRAY = re.compile(r"\[((?:\s*0x[0-9a-fA-F]{2},){32})\s*\]", re.MULTILINE)

HEADER = """\
//! Vendored `halo2_poseidon` P128Pow5T3 parameters and permutation test vectors.
//!
//! These pin ragu's Poseidon permutation to an external reference. The
//! parameters are Orchard's deployed instantiation (t=3, rate 2, alpha 5, 8
//! full and 56 partial rounds over each Pasta base field) and the vectors are
//! halo2's, which are transcribed from zcash-test-vectors'
//! `orchard_poseidon/permute`. Both are fixed by deployed consensus, so they
//! are vendored rather than pulled in as a dependency: there is no upstream
//! drift to track.
//!
//! Ragu ships a different instantiation (t=5, rate 4). What transfers is the
//! permutation *itself* -- round ordering, sbox placement, the full/partial
//! split, MDS application, and the point at which round constants are added --
//! all of which `Permutation` implements generically over
//! [`PoseidonPermutation`](ragu_arithmetic::PoseidonPermutation). Running it at
//! halo2's parameters is what lets an external vector speak to it.
//!
//! Generated by `qa/params/gen_halo2_vectors.py`; do not edit by hand.

use ragu_arithmetic::PoseidonPermutation;
use ragu_pasta::{Fp, Fq, fp, fq};
"""

PARAMS_TEMPLATE = """
/// Orchard's P128Pow5T3 parameters over {field_doc}.
pub(crate) struct {struct_name};

impl PoseidonPermutation<{field}> for {struct_name} {{
    const T: usize = 3;
    const RATE: usize = 2;
    const FULL_ROUNDS: usize = 8;
    const PARTIAL_ROUNDS: usize = 56;
    const ALPHA: isize = 5;

    fn round_constants(&self) -> impl Iterator<Item = &[{field}]> {{
        {prefix}_ROUND_CONSTANTS.iter().copied()
    }}

    fn mds_matrix(&self) -> impl ExactSizeIterator<Item = &[{field}]> {{
        {prefix}_MDS.iter().copied()
    }}
}}
"""


def parse_constants(path, t=3, rounds=64):
    values = []
    for match in FROM_RAW.finditer(path.read_text()):
        limbs = [int(x.replace("_", ""), 16) for x in match.group(1).split(",") if x.strip()]
        values.append(sum(limb << (64 * i) for i, limb in enumerate(limbs)))
    flat, rest = values[: rounds * t], values[rounds * t :]
    round_constants = [flat[r * t : (r + 1) * t] for r in range(rounds)]
    mds = [rest[i * t : (i + 1) * t] for i in range(t)]
    return round_constants, mds


def parse_vectors(path, field):
    text = path.read_text()
    section = text[text.index(f"pub mod {field}") :]
    end = section.index("pub mod ", 1) if "pub mod " in section[1:] else len(section)
    section = section[:end]
    permute = section[section.index("pub fn permute") : section.index("pub fn hash")]

    words = []
    for match in BYTE_ARRAY.finditer(permute):
        octets = [int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", match.group(1))]
        words.append(int.from_bytes(bytes(octets), "little"))

    if len(words) % 6 != 0:
        raise ValueError(f"{field}: expected 6 words per vector, parsed {len(words)}")
    return [(words[i : i + 3], words[i + 3 : i + 6]) for i in range(0, len(words), 6)]


def render_element(macro, value):
    return f"{macro}!(0x{value:064x})"


def render_rows(macro, rows, indent="    "):
    out = []
    for row in rows:
        cells = ",\n".join(f"{indent}    {render_element(macro, v)}" for v in row)
        out.append(f"{indent}&[\n{cells},\n{indent}],")
    return "\n".join(out)


def render_vectors(macro, field, vectors, prefix):
    lines = [
        f"/// halo2's permutation test vectors over `{field}`, as "
        "`(initial_state, final_state)`.",
        f"pub(crate) const {prefix}_PERMUTE_VECTORS: &[([{field}; 3], [{field}; 3])] = &[",
    ]
    for initial, final in vectors:
        lines.append("    (")
        for state in (initial, final):
            lines.append("        [")
            lines.extend(f"            {render_element(macro, v)}," for v in state)
            lines.append("        ],")
        lines.append("    ),")
    lines.append("];")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--halo2-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    src = args.halo2_dir / "halo2_poseidon" / "src"
    out = args.out or (
        Path(__file__).resolve().parents[2]
        / "crates/ragu_primitives/src/poseidon_halo2_vectors.rs"
    )

    chunks = [HEADER]
    for name, field, macro, prefix, field_doc in (
        ("fp", "Fp", "fp", "FP", "Pallas's base field"),
        ("fq", "Fq", "fq", "FQ", "Vesta's base field"),
    ):
        round_constants, mds = parse_constants(src / f"{name}.rs")
        vectors = parse_vectors(src / "test_vectors.rs", name)

        chunks.append(
            PARAMS_TEMPLATE.format(
                field=field, field_doc=field_doc,
                struct_name=f"P128Pow5T3{field}", prefix=prefix,
            )
        )
        chunks.append(
            f"const {prefix}_ROUND_CONSTANTS: &[&[{field}]] = &[\n"
            f"{render_rows(macro, round_constants)}\n];\n"
        )
        chunks.append(f"const {prefix}_MDS: &[&[{field}]] = &[\n{render_rows(macro, mds)}\n];\n")
        chunks.append(render_vectors(macro, field, vectors, prefix) + "\n")

        print(
            f"{field}: {len(round_constants) * 3} round constants, "
            f"{len(mds)}x{len(mds[0])} MDS, {len(vectors)} permutation vectors",
            file=sys.stderr,
        )

    out.write_text("\n".join(chunks).replace("\n\n\n", "\n\n"))
    print(f"wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
