import Clean.Circuit
import Clean.Utils.Primes
import Ragu.Circuits.Element.AllocSquare
import Ragu.Circuits.Element.Mul
import Ragu.Circuits.Point.Spec

namespace Ragu.Circuits.Point.Alloc
variable {p : ℕ} [Fact p.Prime]

-- 3 AllocMul instances: idx for AllocSquare(x), idx+1 for Mul(x,x²), idx+2 for AllocSquare(y)
def main (curveParams : Spec.CurveParams p) (idx : ℕ) (_input : Unit) : Circuit (F p) (Var Spec.Point (F p)) := do
  let ⟨x, x2⟩ ← Element.AllocSquare.circuit idx default
  let x3 ← Element.Mul.circuit (idx + 1) ⟨x, x2⟩
  let ⟨y, y2⟩ ← Element.AllocSquare.circuit (idx + 2) default

  -- NOTE: the constant (b * 1) is not simplified to b to syntactically
  -- match constraints generated by Ragu
  assertZero ((x3 + (curveParams.b * 1)) - y2)
  return ⟨x, y⟩

def Assumptions (idx : ℕ) (_input : Unit) (data : ProverData (F p)) :=
  Element.AllocSquare.Assumptions idx () data ∧
  Element.Mul.Assumptions (idx + 1) ⟨(Core.AllocMul.readRow data idx).x, (Core.AllocMul.readRow data idx).z⟩ data ∧
  Element.AllocSquare.Assumptions (idx + 2) () data

def Spec (curveParams : Spec.CurveParams p) (_input : Unit) (out : Spec.Point (F p)) (_data : ProverData (F p)) :=
  out.isOnCurve curveParams

instance elaborated (curveParams : Spec.CurveParams p) (idx : ℕ) : ElaboratedCircuit (F p) unit Spec.Point where
  main := main curveParams idx
  localLength _ := 9

theorem soundness (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit.Soundness (F p) (elaborated curveParams idx) (Spec curveParams) := by
  circuit_proof_start
  simp [circuit_norm, Spec.Point.isOnCurve,
    Element.AllocSquare.circuit, Element.AllocSquare.Spec,
    Element.Mul.circuit, Element.Mul.Spec, Element.Mul.main] at h_holds ⊢
  obtain ⟨c1, c2, c3, c4⟩ := h_holds
  rw [add_neg_eq_zero, c2, c1, c3] at c4
  rw [←c4]
  ring

theorem completeness (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit.Completeness (F p) (elaborated curveParams idx) (Assumptions idx) := by
  sorry

def circuit (curveParams : Spec.CurveParams p) (idx : ℕ) : GeneralFormalCircuit (F p) unit Spec.Point :=
  {
    (elaborated curveParams idx) with
    Assumptions := Assumptions idx,
    Spec := (Spec curveParams),
    soundness := soundness curveParams idx,
    completeness := completeness curveParams idx
  }

end Ragu.Circuits.Point.Alloc
