import Ragu.Fingerprint
import Ragu.Instances

namespace Ragu.Fingerprint

/-- Every exported circuit instance, paired with its Lean module name.

Autogenerated by `lean_extraction`; do not edit. Used by the `fingerprints`
executable, whose output CI compares against
`cargo run -p lean_extraction -- fingerprint`. -/
def instances : List (String × Ragu.Core.Statements.FormalInstance) := [
  ("Ragu.Instances.Point.AllocFp", Ragu.Instances.Point.AllocFp.formal_instance),
  ("Ragu.Instances.Point.AllocFq", Ragu.Instances.Point.AllocFq.formal_instance),
  ("Ragu.Instances.Point.Double", Ragu.Instances.Point.Double.formal_instance),
  ("Ragu.Instances.Point.DoubleAndAddIncomplete", Ragu.Instances.Point.DoubleAndAddIncomplete.formal_instance),
  ("Ragu.Instances.Point.AddIncomplete", Ragu.Instances.Point.AddIncomplete.formal_instance),
  ("Ragu.Instances.Point.ConditionalEndo", Ragu.Instances.Point.ConditionalEndo.formal_instance),
  ("Ragu.Instances.Point.ConditionalNegate", Ragu.Instances.Point.ConditionalNegate.formal_instance),
  ("Ragu.Instances.Element.Mul", Ragu.Instances.Element.Mul.formal_instance),
  ("Ragu.Instances.Element.Square", Ragu.Instances.Element.Square.formal_instance),
  ("Ragu.Instances.Element.Alloc", Ragu.Instances.Element.Alloc.formal_instance),
  ("Ragu.Instances.Element.AllocSquare", Ragu.Instances.Element.AllocSquare.formal_instance),
  ("Ragu.Instances.Element.DivNonzero", Ragu.Instances.Element.DivNonzero.formal_instance),
  ("Ragu.Instances.Element.FoldN3", Ragu.Instances.Element.FoldN3.formal_instance),
  ("Ragu.Instances.Element.FoldN7", Ragu.Instances.Element.FoldN7.formal_instance),
  ("Ragu.Instances.Element.EnforceRootOfUnityK2", Ragu.Instances.Element.EnforceRootOfUnityK2.formal_instance),
  ("Ragu.Instances.Element.EnforceRootOfUnityK5", Ragu.Instances.Element.EnforceRootOfUnityK5.formal_instance),
  ("Ragu.Instances.Element.EnforceZero", Ragu.Instances.Element.EnforceZero.formal_instance),
  ("Ragu.Instances.Element.Invert", Ragu.Instances.Element.Invert.formal_instance),
  ("Ragu.Instances.Element.InvertWith", Ragu.Instances.Element.InvertWith.formal_instance),
  ("Ragu.Instances.Element.EnforceNonzero", Ragu.Instances.Element.EnforceNonzero.formal_instance),
  ("Ragu.Instances.NonzeroBank.ScopeK2", Ragu.Instances.NonzeroBank.ScopeK2.formal_instance),
  ("Ragu.Instances.Element.IsEqual", Ragu.Instances.Element.IsEqual.formal_instance),
  ("Ragu.Instances.Element.IsZero", Ragu.Instances.Element.IsZero.formal_instance),
  ("Ragu.Instances.Core.Mul", Ragu.Instances.Core.Mul.formal_instance),
  ("Ragu.Instances.Boolean.Alloc", Ragu.Instances.Boolean.Alloc.formal_instance),
  ("Ragu.Instances.Boolean.And", Ragu.Instances.Boolean.And.formal_instance),
  ("Ragu.Instances.Boolean.ConditionalSelect", Ragu.Instances.Boolean.ConditionalSelect.formal_instance),
  ("Ragu.Instances.Boolean.ConditionalEnforceEqual", Ragu.Instances.Boolean.ConditionalEnforceEqual.formal_instance)
]

end Ragu.Fingerprint
