use alloc::{vec, vec::Vec};

use crate::ff::PrimeField;

/// Radix-2 evaluation domain of size $n = 2^k$ generated by powers of a
/// primitive $n$-th root of unity $\omega$, consisting of the set
/// $\{1, \omega, \omega^2, \ldots, \omega^{n-1}\}$.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Domain<F> {
    /// $n$, the size of the domain
    n: usize,
    /// $\log_2(n)$, exponent such that $n = 2^{log2_n}$,
    /// where the domain size $n$ must always be a power of two
    log2_n: u32,
    /// The primitive $n$-th root of unity in the field
    omega: F,
    /// Inverse of the primitive $n$-th root of unity in the field
    omega_inv: F,
    /// Inverse of $n$ in the field (as an integer) for inverse FFTs
    n_inv: F,
}

impl<F: PrimeField> Domain<F> {
    /// Initializes a new domain of size $2^k$.
    ///
    /// # Panics
    ///
    /// Panics if `k` exceeds the field's 2-adicity `F::S`, or if the domain
    /// size $2^k$ does not fit in a `usize` on the current target.
    pub fn new(k: u32) -> Self {
        assert!(
            k <= F::S,
            "tried to create a domain of size 2^{} in a field with 2-adicity {}",
            k,
            F::S
        );
        assert!(
            k < usize::BITS,
            "domain of size 2^{} does not fit in usize on this target",
            k
        );

        // Deriving the generator costs `F::S - k` squarings on every
        // construction; eliminating this would require a precomputed table of
        // roots of unity indexed by `k`.
        let mut omega = F::ROOT_OF_UNITY;
        let mut omega_inv = F::ROOT_OF_UNITY_INV;
        for _ in k..F::S {
            omega = omega.square();
            omega_inv = omega_inv.square();
        }

        Domain {
            n: 1 << k,
            log2_n: k,
            omega,
            omega_inv,
            n_inv: F::TWO_INV.pow_vartime([k as u64]),
        }
    }

    /// The size of the domain.
    pub fn n(&self) -> usize {
        self.n
    }

    /// The $\log_2(n)$ of this domain of size $n$.
    pub fn log2_n(&self) -> u32 {
        self.log2_n
    }

    /// Returns the generator of the domain.
    pub fn omega(&self) -> F {
        self.omega
    }

    /// Returns the inverse of the generator of the domain.
    pub fn omega_inv(&self) -> F {
        self.omega_inv
    }

    /// Returns $n^{-1}$, the inverse of the domain size embedded in the field.
    pub fn n_inv(&self) -> F {
        self.n_inv
    }

    /// Returns an iterator over the elements of the domain in order:
    /// $1, \omega, \omega^2, \ldots, \omega^{n-1}$.
    ///
    /// The iterator is lazy and computes each element from the previous one
    /// with a single multiplication; collecting it materializes all $n$
    /// elements at once. The returned type is deliberately
    /// opaque: the underlying iterator computes elements front-to-back, so
    /// exposing `DoubleEndedIterator` would yield wrong values under `rev()`.
    pub fn elements(&self) -> impl ExactSizeIterator<Item = F> {
        let omega = self.omega;
        let mut cur = F::ONE;
        (0..self.n).map(move |_| {
            let tmp = cur;
            cur *= omega;
            tmp
        })
    }

    /// Computes $x^n$ by `log2_n` successive squarings.
    ///
    /// This is faster than a generic exponentiation, and the exponent (the
    /// domain size) is public, so no side-channel protection is needed.
    fn pow_n(&self, x: F) -> F {
        (0..self.log2_n).fold(x, |acc, _| acc.square())
    }

    /// Evaluates the vanishing polynomial $v(x) = x^n - 1$ of the domain.
    pub fn vanishing(&self, x: F) -> F {
        self.pow_n(x) - F::ONE
    }

    /// Returns true if `x` is an element of this domain.
    pub fn contains(&self, x: F) -> bool {
        self.vanishing(x) == F::ZERO
    }

    /// Computes the radix2 discrete Fourier transform (DFT) of a slice of
    /// generic ring elements using the Cooley-Tukey FFT algorithm.
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ring_fft<R: crate::fft::Ring<F = F>>(&self, input: &mut [R::R]) {
        assert_eq!(
            input.len(),
            self.n,
            "input length must equal the domain size n = 2^{}",
            self.log2_n
        );
        crate::fft::fft::<R>(input, self.omega, self.log2_n);
    }

    /// Performs the inverse operation of [`Self::ring_fft`].
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ring_ifft<R: crate::fft::Ring<F = F>>(&self, input: &mut [R::R]) {
        assert_eq!(
            input.len(),
            self.n,
            "input length must equal the domain size n = 2^{}",
            self.log2_n
        );
        crate::fft::fft::<R>(input, self.omega_inv, self.log2_n);

        for input in input.iter_mut() {
            R::scale_assign(input, self.n_inv);
        }
    }

    /// Computes the radix2 discrete Fourier transform (DFT) of a slice of field
    /// elements using the Cooley-Tukey FFT algorithm.
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn fft(&self, input: &mut [F]) {
        self.ring_fft::<crate::fft::FFTField<F>>(input);
    }

    /// Performs the inverse operation of [`Self::fft`].
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ifft(&self, input: &mut [F]) {
        self.ring_ifft::<crate::fft::FFTField<F>>(input);
    }

    /// This function produces the evaluations of Lagrange basis polynomials
    /// $\ell_i(x)$ for the domain generated by powers of $\omega$ where
    /// $\omega$ is an `n`-th primitive root of unity. Returns a vector with
    /// `amount` number of evaluations (starting at $\omega^0$), or `Err(i)`
    /// if `x` is the domain element $\omega^i$. In the latter case the
    /// evaluations are trivial: $\ell_i(x) = 1$ and all others are zero.
    ///
    /// # Panics
    ///
    /// Panics if the provided `amount` exceeds `n`.
    ///
    /// # Implementation
    ///
    /// The Lagrange basis polynomials are given for a domain $D$ of size $n$
    /// generated by powers of $\omega$ where $\omega$ is a primitive $n$-th
    /// root of unity. The vanishing polynomial for this domain is
    ///
    /// $$ v(X) = \prod_{i=0}^{n - 1} (X - \omega^i) = X^n - 1. $$
    ///
    /// and so the Lagrange basis polynomials are given by
    ///
    /// $$ \ell_i(X) = \frac{(X^n - 1) b_i}{X - \omega^i} $$
    ///
    /// where
    ///
    /// $$ b_i = \prod_{j=0, j \neq i}^{n - 1} (\omega^i - \omega^j)^{-1} =
    /// \frac{\omega^i}{n} $$
    ///
    /// is the barycentric weight of $\omega^i$. Thus, given some point $x \in
    /// \mathbb{F} \setminus D$ we can compute
    ///
    /// $$ \ell_i(x) = (x - \omega^i)^{-1} \cdot \frac{(x^n - 1) \omega^i}{n}.$$
    ///
    /// Most of the work of computing these values can be shared using
    /// Montgomery's trick.
    pub fn lagrange_evals(&self, x: F, amount: usize) -> Result<Vec<F>, usize> {
        assert!(amount <= self.n);

        let vanishing = self.vanishing(x); // x^n - 1
        if vanishing == F::ZERO {
            // By definition, `x` must be an element of the domain itself. This
            // means that the coefficients returned would have a trivial value:
            // all zeroes except for the $i$-th coefficient which would be 1.

            // The implementation below relies on `x` not being in the domain.
            // Therefore, we return the index of `x` within the domain so that
            // this case can be handled explicitly (and more efficiently) by
            // the caller.
            return Err(self.index_of(x));
        }

        // Compute (x - \omega^i)^{-1} for i = 0, ..., amount - 1
        let mut denominators: Vec<F> = (0..amount)
            .scan(F::ONE, |acc, _| {
                let tmp = x - *acc;
                *acc *= self.omega;
                Some(tmp)
            })
            .collect();
        {
            let mut scratch = vec![F::ZERO; denominators.len()];
            crate::ff::BatchInverter::invert_with_external_scratch(&mut denominators, &mut scratch);
        }

        Ok(
            // (x - \omega^i)^{-1} \cdot \frac{(x^n - 1) \omega^i}{n}
            denominators
                .into_iter()
                .scan(vanishing * self.n_inv, move |numerator, denominator| {
                    let tmp = (*numerator) * denominator;
                    *numerator *= self.omega;
                    Some(tmp)
                })
                .collect(),
        )
    }

    /// Returns the index $i \in [0, n)$ such that $\omega^i$ equals `x`,
    /// assuming `x` is an element of the domain. If `x` is not in the domain,
    /// the returned index is meaningless.
    ///
    /// Computes the discrete logarithm of `x` bit by bit: the domain is the
    /// order-$2^k$ subgroup generated by $\omega$, in which $\omega^{2^{k-1}}$
    /// is the unique element of order 2, so raising to the power $2^{k-1-j}$
    /// exposes bit $j$ of the logarithm once the lower bits have been cleared.
    /// This takes $O(k^2)$ squarings rather than the $O(2^k)$ multiplications
    /// of a linear scan.
    fn index_of(&self, mut x: F) -> usize {
        let mut index = 0usize;
        let mut gen_inv = self.omega_inv; // omega^-(2^j) at iteration j
        for j in 0..self.log2_n {
            // t = x^(2^(k-1-j)) is 1 or -1; -1 means bit j of the index is set.
            let mut t = x;
            for _ in 0..(self.log2_n - 1 - j) {
                t = t.square();
            }
            if t != F::ONE {
                index |= 1 << j;
                x *= gen_inv;
            }
            gen_inv = gen_inv.square();
        }
        index
    }
}

#[test]
fn test_fft() {
    use crate::{eval, ff::Field, pasta_curves::Fp as F};

    for log2_n in 1..=8 {
        let params = Domain::<F>::new(log2_n);

        let coeffs = (0..params.n)
            .map(|i| F::DELTA.pow([(i + 1) as u64]))
            .collect::<Vec<_>>();
        let mut evals = coeffs.clone();

        params.fft(&mut evals);

        {
            let mut p = F::ONE;
            for e in evals.iter().take(params.n) {
                assert_eq!(*e, eval(&coeffs, p));
                p *= params.omega;
            }
        }

        let mut coeffs_recovered = evals.clone();
        params.ifft(&mut coeffs_recovered);
        assert_eq!(coeffs, coeffs_recovered);
    }
}

#[test]
fn test_lagrange_evals() {
    use alloc::vec;

    use crate::{eval, ff::Field, pasta_curves::Fp as F};

    let params = Domain::<F>::new(5);

    let mut lagrange_polys = vec![];
    for i in 0..params.n {
        assert_eq!(
            params.lagrange_evals(params.omega.pow([i as u64]), params.n),
            Err(i)
        );
        let mut tmp = vec![F::ZERO; params.n];
        tmp[i] = F::ONE;
        params.ifft(&mut tmp);
        for j in 0..params.n {
            assert_eq!(
                eval(&tmp, params.omega.pow([j as u64])),
                if i == j { F::ONE } else { F::ZERO }
            );
        }
        lagrange_polys.push(tmp);
    }

    let x = F::DELTA;

    let expected = params.lagrange_evals(x, params.n).unwrap();
    for (i, expected) in expected.iter().enumerate() {
        assert_eq!(eval(&lagrange_polys[i], x), *expected);
    }
}

#[test]
fn test_contains() {
    use crate::{ff::Field, pasta_curves::Fp as F};

    let domain = Domain::<F>::new(5);

    // All powers of omega should be in the domain
    let mut omega_pow = F::ONE;
    for _ in 0..domain.n() {
        assert!(domain.contains(omega_pow), "omega^i should be in domain");
        omega_pow *= domain.omega();
    }

    // Random field elements should (almost certainly) not be in the domain
    assert!(!domain.contains(F::from(2u64)));
    assert!(!domain.contains(F::from(3u64)));
    assert!(!domain.contains(F::DELTA));
}

#[test]
fn test_elements() {
    use crate::{ff::Field, pasta_curves::Fp as F};

    let domain = Domain::<F>::new(5);

    let elements = domain.elements();
    assert_eq!(elements.len(), domain.n());

    let mut omega_pow = F::ONE;
    for element in elements {
        assert_eq!(element, omega_pow);
        omega_pow *= domain.omega();
    }
}

#[test]
fn test_new_constructs_consistent_domains() {
    use crate::{ff::Field, pasta_curves::Fp as F};

    for k in 1..=8 {
        let domain = Domain::<F>::new(k);
        assert_eq!(domain.omega() * domain.omega_inv(), F::ONE);
        assert_eq!(domain.n_inv() * F::from(domain.n() as u64), F::ONE);
        // omega has order exactly n: omega^n = 1 but omega^(n/2) != 1.
        assert_eq!(domain.pow_n(domain.omega()), F::ONE);
        assert_ne!(domain.omega().pow([(domain.n() / 2) as u64]), F::ONE);
    }

    let trivial = Domain::<F>::new(0);
    assert_eq!(trivial.n(), 1);
    assert_eq!(trivial.omega(), F::ONE);
    assert_eq!(trivial.n_inv(), F::ONE);
}

#[cfg(test)]
mod proptests {
    use proptest::prelude::*;

    use super::*;
    use crate::pasta_curves::Fp as F;

    fn arb_fe() -> impl Strategy<Value = F> {
        (any::<u64>(), any::<u64>())
            .prop_map(|(a, b)| F::from(a) + F::from(b) * F::MULTIPLICATIVE_GENERATOR)
    }

    proptest! {
        #[test]
        fn fft_ifft_roundtrip(log2_n in 1u32..=8, seed in arb_fe()) {
            let domain = Domain::<F>::new(log2_n);
            let coeffs: Vec<F> = (0..domain.n())
                .map(|i| seed * F::from((i + 1) as u64))
                .collect();
            let mut buf = coeffs.clone();
            domain.fft(&mut buf);
            domain.ifft(&mut buf);
            prop_assert_eq!(buf, coeffs);
        }
    }
}

#[test]
#[should_panic]
fn test_domain_exceeds_max_boundary_panics() {
    use crate::pasta_curves::Fp as F;

    let over_max = F::S + 1;
    let _domain = Domain::<F>::new(over_max);
}
